<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HDC3-L-128FX5H" ignored="1" name="Default test" tests="3" failures="3" timestamp="2021-09-22T11:54:41 IST" time="2.571" errors="0">
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.899" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="address line1 key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: address line1 key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.ValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidingCustomerWithValidSecrectkey -->
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.899" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="address line1 key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: address line1 key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.ValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidingCustomerWithValidSecrectkey -->
  <testcase name="ValidingCustomerWithValidSecrectkey" time="2.489" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="address line1 key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: address line1 key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.ValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidingCustomerWithValidSecrectkey -->
  <testcase name="inValidingCustomerWithValidSecrectkey" time="0.0" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <ignored/>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
</testsuite> <!-- Default test -->
