<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" guice-stage="DEVELOPMENT" name="Failed suite [API TESTING]" parallel="methods">
  <listeners>
    <listener class-name="com.accenture.APITestingFrameWork.listeners.ExtentListeners"/>
  </listeners>
  <test thread-count="2" name="Regressioin(failed)" parallel="methods">
    <classes>
      <class name="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
        <methods>
          <include name="deleteCustomer" invocation-numbers="1 2 4 0 3"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest -->
      <class name="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
        <methods>
          <include name="inValidingCustomerWithValidSecrectkey" invocation-numbers="0 1"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable -->
    </classes>
  </test> <!-- Regressioin(failed) -->
</suite> <!-- Failed suite [API TESTING] -->
