<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HDC3-L-128FX5H" ignored="3" name="Regressioin" tests="18" failures="7" timestamp="2021-09-23T17:20:16 IST" time="4.555" errors="0">
  <testcase name="inValidingCustomerWithValidSecrectkey" time="2.089" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTableTest.java:73)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="inValidingCustomerWithValidSecrectkey" time="2.089" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTableTest.java:73)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="deleteCustomer" time="2.224" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="2.226" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="2.279" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="2.284" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="2.284" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="listAllCustomers" time="1.304" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.275" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.304" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.361" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest"/>
  <testcase name="listSingleCustomer" time="0.512" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="listSingleCustomer" time="0.514" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="listSingleCustomer" time="0.517" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="listSingleCustomer" time="0.529" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="updateSingleCustomer" time="0.638" classname="com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest"/>
  <testcase name="updateSingleCustomer" time="0.65" classname="com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest"/>
  <testcase name="updateSingleCustomer" time="0.681" classname="com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest"/>
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.accenture.APITestingFrameWork.base.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.accenture.APITestingFrameWork.base.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.accenture.APITestingFrameWork.base.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
</testsuite> <!-- Regressioin -->
